#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'sudo'
cookbook 'mysql'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'ulimit', '= 0.2.0' # FIXME: https://github.com/bmhatfield/chef-ulimit/issues/10
cookbook 'redisio', '~> 1.7.0'
cookbook 'openssl'
cookbook 'geoip'
cookbook 'zip'
cookbook 'memcached'
cookbook 'libmagic', :git => 'git@github.com:froschi/chef-cookbook-libmagic.git'
cookbook 'libcurl', :git => 'git@github.com:theodi/chef-libcurl.git'
